package com.aldogg.sorter.generators;

public enum GeneratorFunctions {
    SHUFFLED,
    SHUFFLED_16_VALUES,
    ALL_EQUAL,
    ASCENDING,
    DESCENDING,
    PIPE_ORGAN,
    PUSH_FRONT,
    PUSH_MIDDLE,
    ASCENDING_SAWTOOTH,
    DESCENDING_SAWTOOTH,
    ALTERNATING,
    ALTERNATING_16_VALUES,
    RANDOM_INTEGER_RANGE,
    RANDOM_REAL_RANGE,
}
